name: score
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: '>=3.4.3 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  dots_indicator: ^3.0.0
  firebase_core: ^3.5.0
  firebase_auth: ^5.3.0
  cloud_firestore: ^5.3.0
  firebase_storage: ^12.2.0
  image_picker: ^1.1.2
  fluttertoast: ^8.2.8
  fl_chart: ^0.69.0
  permission_handler: ^11.3.1
  intl: ^0.19.0
  file_picker: ^8.1.2
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
flutter:
  uses-material-design: true
  assets:
    - assets/logo.jpg
    - assets/logo2.jpg
    - assets/splash_white.png
    - assets/student.png
    - assets/event.png
    - assets/scorelogin.png

